services:
  # Flask Backend with Gunicorn
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-backend
    hostname: flask-backend
    restart: always
    shm_size: 2gb
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - app-network

  # MySQL Database
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - app-network

  # Nginx for Frontend
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/var/www/html
    depends_on:
      - flask
    networks:
      - app-network

networks:
  app-network:
    driver: bridge